name: Deploay React App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Nodejs
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
  
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to surge
      run: surge ./build reactapp-ts2.surge.sh --token ${{ secrets.surge_token }}
